# Generated by Django 5.2.8 on 2025-12-01 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioTransito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(help_text='Máximo 500 caracteres', max_length=500)),
                ('categoria', models.CharField(choices=[('trafico', 'Tráfico'), ('seguridad', 'Seguridad'), ('ruta_alt', 'Ruta Alternativa'), ('consejo', 'Consejo General'), ('otro', 'Otro')], default='consejo', max_length=20)),
                ('ubicacion_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ubicacion_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_transito', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentario de Tránsito',
                'verbose_name_plural': 'Comentarios de Tránsito',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
