# Generated by Django 5.2.8 on 2025-12-01 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiMapa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariotransito',
            name='nombre_anonimo',
            field=models.CharField(default='Anónimo', help_text='Nombre mostrado cuando no hay usuario registrado', max_length=100),
        ),
        migrations.AlterField(
            model_name='comentariotransito',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Opcional por ahora - se hará obligatorio al implementar autenticación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_transito', to=settings.AUTH_USER_MODEL),
        ),
    ]
